from __future__ import annotations

from typing import Any

CONFIG_VALUE_PATHS: dict[str, str] = {
    "lifecycle.approval_timeout_hours": "lifecycle.approval_timeout_hours",
    "lifecycle.watch_minutes": "lifecycle.watch_minutes",
    "lifecycle.closed_recall_days": "lifecycle.closed_recall_days",
    "retention.raw_message_days": "retention.raw_message_days",
    "retention.resource_days": "retention.resource_days",
    "daemon.tick_interval_seconds": "daemon.tick_interval_seconds",
    "daemon.overlap_seconds": "daemon.overlap_seconds",
    "health.interval_seconds": "health.interval_seconds",
    "health.retry_interval_seconds": "health.retry_interval_seconds",
    "health.timeout_seconds": "health.timeout_seconds",
    "storage.sqlite_path": "storage.sqlite_path",
    "storage.resource_dir": "storage.resource_dir",
    "storage.max_resource_bytes": "storage.max_resource_bytes",
    "storage.max_resource_dir_bytes": "storage.max_resource_dir_bytes",
    "agent_backend.provider": "agent_backend.provider",
    "agent_backend.working_dir": "agent_backend.working_dir",
    "agent_backend.config_scope": "agent_backend.config_scope",
    "agent_backend.auto_context": "agent_backend.auto_context",
    "agent_backend.explicit_context.skills": "agent_backend.explicit_context.skills",
    "agent_backend.hermes.mode": "agent_backend.hermes.mode",
    "agent_backend.hermes.model": "agent_backend.hermes.model",
    "agent_backend.hermes.provider": "agent_backend.hermes.provider",
    "agent_backend.hermes.router_max_turns": "agent_backend.hermes.router_max_turns",
    "agent_backend.hermes.session_max_turns": "agent_backend.hermes.session_max_turns",
    "agent_backend.hermes.timeout_seconds": "agent_backend.hermes.timeout_seconds",
    "agent_backend.hermes.path": "agent_backend.hermes.path",
    "agent_backend.hermes.health_url": "agent_backend.hermes.health_url",
    "agent_backend.hermes.api_key_env": "agent_backend.hermes.api_key_env",
    "agent_backend.codex.model": "agent_backend.codex.model",
    "agent_backend.codex.timeout_seconds": "agent_backend.codex.timeout_seconds",
    "agent_backend.codex.path": "agent_backend.codex.path",
    "agent_backend.claude_code.model": "agent_backend.claude_code.model",
    "agent_backend.claude_code.timeout_seconds": "agent_backend.claude_code.timeout_seconds",
    "agent_backend.claude_code.path": "agent_backend.claude_code.path",
    "tool_permissions": "tool_permissions",
    "owner.open_id": "owner.open_id",
    "owner.name": "owner.name",
    "lark_cli.path": "lark_cli.path",
    "lark_cli.timeout_seconds": "lark_cli.timeout_seconds",
    "logging.jsonl_path": "logging.jsonl_path",
    "logging.level": "logging.level",
    "logging.console": "logging.console",
    "logging.text_path": "logging.text_path",
    "debug.save_full_agent_io": "debug.save_full_agent_io",
}


def settings_catalog() -> dict[str, Any]:
    return {
        "version": 1,
        "entries": [dict(entry) for entry in _SETTINGS_CATALOG],
    }


def _entry(
    key: str,
    label: str,
    description: str,
    *,
    source: str,
    scope: str,
    visibility: str,
    editable_v1: bool | str,
    requires_restart: bool,
    audit_behavior: str,
    write_boundary: str | None,
    help: str | None = None,
) -> dict[str, Any]:
    return {
        "key": key,
        "label": label,
        "description": description,
        "help": help,
        "source": source,
        "scope": scope,
        "visibility": visibility,
        "editable_v1": editable_v1,
        "requires_restart": requires_restart,
        "audit_behavior": audit_behavior,
        "write_boundary": write_boundary,
    }


_SETTINGS_CATALOG: list[dict[str, Any]] = [
    _entry(
        "policy.global.p2p_auto_reply",
        "P2P auto reply",
        "Allow one-to-one chats to auto-reply when reply gates pass.",
        source="product_policy_store",
        scope="global_policy",
        visibility="normal",
        editable_v1=True,
        requires_restart=False,
        audit_behavior="policy_audits",
        write_boundary="PATCH /api/policy/global",
    ),
    _entry(
        "policy.global.unknown_group_auto_reply",
        "Unknown group auto reply",
        "Allow groups without explicit chat policy to auto-reply when reply gates pass.",
        source="product_policy_store",
        scope="global_policy",
        visibility="normal",
        editable_v1=True,
        requires_restart=False,
        audit_behavior="policy_audits",
        write_boundary="PATCH /api/policy/global",
        help="Applies only to groups that do not have their own Product Policy row.",
    ),
    _entry(
        "policy.global.default_bot_joined",
        "Default bot joined",
        "Default bot availability for chats without explicit policy.",
        source="product_policy_store",
        scope="global_policy",
        visibility="advanced",
        editable_v1=True,
        requires_restart=False,
        audit_behavior="policy_audits",
        write_boundary="PATCH /api/policy/global",
    ),
    _entry(
        "policy.global.default_reply_identity",
        "Default reply identity",
        "Default identity strategy for chats without explicit policy.",
        source="product_policy_store",
        scope="global_policy",
        visibility="advanced",
        editable_v1=True,
        requires_restart=False,
        audit_behavior="policy_audits",
        write_boundary="PATCH /api/policy/global",
        help="bot_preferred can use the bot and fall back to your user identity when fallback is allowed.",
    ),
    _entry(
        "policy.global.default_allow_user_fallback",
        "Default user fallback",
        "Default permission to fall back to user identity for bot-preferred replies.",
        source="product_policy_store",
        scope="global_policy",
        visibility="advanced",
        editable_v1=True,
        requires_restart=False,
        audit_behavior="policy_audits",
        write_boundary="PATCH /api/policy/global",
        help="Only matters when reply identity is bot_preferred.",
    ),
    _entry(
        "policy.global.default_resource_download",
        "Default resource download",
        "Default permission to save downloadable message resources for processing context.",
        source="product_policy_store",
        scope="global_policy",
        visibility="advanced",
        editable_v1=True,
        requires_restart=False,
        audit_behavior="policy_audits",
        write_boundary="PATCH /api/policy/global",
        help="Controls whether eligible Feishu resources may be saved locally for the assistant context.",
    ),
    _entry(
        "policy.chat.name",
        "Chat name",
        "Operator-facing chat label.",
        source="product_policy_store",
        scope="chat_policy",
        visibility="normal",
        editable_v1=True,
        requires_restart=False,
        audit_behavior="policy_audits",
        write_boundary="PATCH /api/policy/chats/{chat_id}",
    ),
    _entry(
        "policy.chat.auto_reply",
        "Auto reply",
        "Allow this chat to auto-reply when all gates pass.",
        source="product_policy_store",
        scope="chat_policy",
        visibility="normal",
        editable_v1=True,
        requires_restart=False,
        audit_behavior="policy_audits",
        write_boundary="PATCH /api/policy/chats/{chat_id}",
    ),
    _entry(
        "policy.chat.bot_joined",
        "Bot joined",
        "Whether the bot is available in this chat for bot replies and resource access.",
        source="product_policy_store",
        scope="chat_policy",
        visibility="normal",
        editable_v1=True,
        requires_restart=False,
        audit_behavior="policy_audits",
        write_boundary="PATCH /api/policy/chats/{chat_id}",
        help="Bot-based replies and resource access depend on the bot being present in the chat.",
    ),
    _entry(
        "policy.chat.reply_identity",
        "Reply identity",
        "Identity strategy for replies in this chat.",
        source="product_policy_store",
        scope="chat_policy",
        visibility="normal",
        editable_v1=True,
        requires_restart=False,
        audit_behavior="policy_audits",
        write_boundary="PATCH /api/policy/chats/{chat_id}",
        help="Choose bot_preferred, bot, or user depending on how replies should be sent.",
    ),
    _entry(
        "policy.chat.allow_user_fallback",
        "Allow user fallback",
        "Let bot-preferred replies fall back to your user identity when the bot cannot reply.",
        source="product_policy_store",
        scope="chat_policy",
        visibility="normal",
        editable_v1=True,
        requires_restart=False,
        audit_behavior="policy_audits",
        write_boundary="PATCH /api/policy/chats/{chat_id}",
        help="Applies only when reply identity is bot_preferred.",
    ),
    _entry(
        "policy.chat.resource_download",
        "Resource download",
        "Allow this chat's downloadable message resources to be saved for processing context.",
        source="product_policy_store",
        scope="chat_policy",
        visibility="normal",
        editable_v1=True,
        requires_restart=False,
        audit_behavior="policy_audits",
        write_boundary="PATCH /api/policy/chats/{chat_id}",
        help="Controls local saving of Feishu message resources for this chat.",
    ),
    _entry(
        "policy.status.initialized",
        "Product Policy initialized",
        "Whether the runtime Product Policy Store has a global policy row.",
        source="runtime_status",
        scope="policy_status",
        visibility="readonly",
        editable_v1=False,
        requires_restart=False,
        audit_behavior="none",
        write_boundary=None,
    ),
    _entry(
        "policy.status.import_diff",
        "Policy Import Diff",
        "Read-only comparison of Policy Import Source with Product Policy Store.",
        source="derived",
        scope="policy_status",
        visibility="readonly",
        editable_v1=False,
        requires_restart=False,
        audit_behavior="none",
        write_boundary=None,
    ),
    _entry(
        "policy.audit.history",
        "Policy audit history",
        "Recent Product Policy changes recorded in the audit table.",
        source="product_policy_store",
        scope="policy_audit",
        visibility="readonly",
        editable_v1=False,
        requires_restart=False,
        audit_behavior="read only",
        write_boundary=None,
    ),
    _entry(
        "policy.import_config",
        "Import config policy",
        "Import Policy Import Source values into Product Policy Store.",
        source="config_yaml",
        scope="policy_import",
        visibility="normal",
        editable_v1="command",
        requires_restart=False,
        audit_behavior="policy_audits",
        write_boundary="POST /api/policy/import-config",
    ),
    _entry(
        "lifecycle.approval_timeout_hours",
        "Approval timeout",
        "Hours before pending approvals become eligible for explicit expiry.",
        source="config_yaml",
        scope="lifecycle",
        visibility="normal",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
        help="Read models mark approvals overdue before an explicit expiry command moves them to expired.",
    ),
    _entry(
        "lifecycle.watch_minutes",
        "Watch window",
        "Minutes a task remains active after activity.",
        source="config_yaml",
        scope="lifecycle",
        visibility="normal",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "lifecycle.closed_recall_days",
        "Closed recall window",
        "Days during which closed tasks may be considered for explicit recall.",
        source="config_yaml",
        scope="lifecycle",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "retention.raw_message_days",
        "Raw message retention",
        "Days to keep raw Feishu message payloads.",
        source="config_yaml",
        scope="retention",
        visibility="normal",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "retention.resource_days",
        "Resource retention",
        "Days to keep downloaded resource files.",
        source="config_yaml",
        scope="retention",
        visibility="normal",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "daemon.tick_interval_seconds",
        "Daemon tick interval",
        "Seconds between daemon polling ticks.",
        source="config_yaml",
        scope="daemon",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "daemon.overlap_seconds",
        "Message overlap window",
        "Look-back seconds added to Feishu message fetches.",
        source="config_yaml",
        scope="daemon",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "health.interval_seconds",
        "Health refresh interval",
        "Seconds between full runtime health refreshes.",
        source="config_yaml",
        scope="health",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "health.retry_interval_seconds",
        "Health retry interval",
        "Seconds to wait before retrying health after a critical failure.",
        source="config_yaml",
        scope="health",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "health.timeout_seconds",
        "Health timeout",
        "Default timeout seconds for health probes.",
        source="config_yaml",
        scope="health",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "storage.sqlite_path",
        "SQLite path",
        "Configured SQLite database path.",
        source="config_yaml",
        scope="storage",
        visibility="diagnostic",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="none",
        write_boundary=None,
    ),
    _entry(
        "storage.resource_dir",
        "Resource directory",
        "Configured local directory for downloaded resources.",
        source="config_yaml",
        scope="storage",
        visibility="diagnostic",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="none",
        write_boundary=None,
    ),
    _entry(
        "storage.max_resource_bytes",
        "Max resource size",
        "Maximum bytes allowed for one downloaded resource.",
        source="config_yaml",
        scope="storage",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "storage.max_resource_dir_bytes",
        "Max resource directory size",
        "Maximum total bytes allowed under the resource directory.",
        source="config_yaml",
        scope="storage",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "agent_backend.provider",
        "Agent provider",
        "Configured agent backend provider.",
        source="config_yaml",
        scope="agent_backend",
        visibility="readonly",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="none",
        write_boundary=None,
    ),
    _entry(
        "agent_backend.working_dir",
        "Agent working directory",
        "Working directory used for agent subprocesses and new task sessions.",
        source="config_yaml",
        scope="agent_backend",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
        help="Null resolves to the config file directory; relative paths are resolved from the config file directory. Existing tasks keep their stored working directory.",
    ),
    _entry(
        "agent_backend.config_scope",
        "Agent config scope",
        "Whether agent CLI calls load user-global configuration or run isolated.",
        source="config_yaml",
        scope="agent_backend",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "agent_backend.auto_context",
        "Agent auto context",
        "Whether agent CLI calls load implicit rules, memory, and default skill context.",
        source="config_yaml",
        scope="agent_backend",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "agent_backend.explicit_context.skills",
        "Explicit skills",
        "Explicit skill paths injected into task-session agent calls.",
        source="config_yaml",
        scope="agent_backend",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "agent_backend.hermes.mode",
        "Hermes health mode",
        "Hermes health-check mode; task processing still uses the local CLI.",
        source="config_yaml",
        scope="agent_backend",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "agent_backend.hermes.model",
        "Hermes model",
        "Optional Hermes model override.",
        source="config_yaml",
        scope="agent_backend",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "agent_backend.hermes.provider",
        "Hermes provider",
        "Optional Hermes provider override.",
        source="config_yaml",
        scope="agent_backend",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "agent_backend.hermes.router_max_turns",
        "Router max turns",
        "Maximum Hermes tool-iteration turns for routing calls.",
        source="config_yaml",
        scope="agent_backend",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "agent_backend.hermes.session_max_turns",
        "Session max turns",
        "Maximum Hermes tool-iteration turns for task-session calls.",
        source="config_yaml",
        scope="agent_backend",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "agent_backend.hermes.timeout_seconds",
        "Hermes timeout",
        "Timeout seconds for Hermes subprocess or health calls.",
        source="config_yaml",
        scope="agent_backend",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "agent_backend.hermes.path",
        "Hermes executable",
        "Optional Hermes executable path.",
        source="config_yaml",
        scope="agent_backend",
        visibility="diagnostic",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="none",
        write_boundary=None,
    ),
    _entry(
        "agent_backend.hermes.health_url",
        "Hermes health URL",
        "Optional HTTP health URL used only for health checks.",
        source="config_yaml",
        scope="agent_backend",
        visibility="diagnostic",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="none",
        write_boundary=None,
    ),
    _entry(
        "agent_backend.hermes.api_key_env",
        "Hermes API key env",
        "Environment variable name for Hermes HTTP health authentication.",
        source="config_yaml",
        scope="agent_backend",
        visibility="diagnostic",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="none",
        write_boundary=None,
    ),
    _entry(
        "agent_backend.codex.model",
        "Codex model",
        "Optional Codex model override.",
        source="config_yaml",
        scope="agent_backend",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "agent_backend.codex.timeout_seconds",
        "Codex timeout",
        "Timeout seconds for Codex subprocess calls.",
        source="config_yaml",
        scope="agent_backend",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "agent_backend.codex.path",
        "Codex executable",
        "Optional Codex executable path.",
        source="config_yaml",
        scope="agent_backend",
        visibility="diagnostic",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="none",
        write_boundary=None,
    ),
    _entry(
        "agent_backend.claude_code.model",
        "Claude Code model",
        "Optional Claude Code model override.",
        source="config_yaml",
        scope="agent_backend",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "agent_backend.claude_code.timeout_seconds",
        "Claude Code timeout",
        "Timeout seconds for Claude Code subprocess calls.",
        source="config_yaml",
        scope="agent_backend",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "agent_backend.claude_code.path",
        "Claude Code executable",
        "Optional Claude Code executable path.",
        source="config_yaml",
        scope="agent_backend",
        visibility="diagnostic",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="none",
        write_boundary=None,
    ),
    _entry(
        "tool_permissions",
        "Tool permissions",
        "Agent backend tool permission profile.",
        source="config_yaml",
        scope="agent_backend",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "owner.open_id",
        "Owner open ID",
        "Configured Feishu owner open_id.",
        source="config_yaml",
        scope="owner",
        visibility="readonly",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="none",
        write_boundary=None,
    ),
    _entry(
        "owner.name",
        "Owner name",
        "Optional operator-facing owner name.",
        source="config_yaml",
        scope="owner",
        visibility="readonly",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="none",
        write_boundary=None,
    ),
    _entry(
        "lark_cli.path",
        "lark-cli executable",
        "Optional lark-cli executable path.",
        source="config_yaml",
        scope="feishu",
        visibility="diagnostic",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="none",
        write_boundary=None,
    ),
    _entry(
        "lark_cli.timeout_seconds",
        "lark-cli timeout",
        "Timeout seconds for lark-cli subprocess calls.",
        source="config_yaml",
        scope="feishu",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "logging.jsonl_path",
        "JSONL log path",
        "Configured structured log path.",
        source="config_yaml",
        scope="logging",
        visibility="diagnostic",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="none",
        write_boundary=None,
    ),
    _entry(
        "logging.level",
        "Log level",
        "Minimum runtime log level.",
        source="config_yaml",
        scope="logging",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "logging.console",
        "Console logging",
        "Whether human-readable runtime logs are also written to stderr.",
        source="config_yaml",
        scope="logging",
        visibility="advanced",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future config audit",
        write_boundary="future ConfigCommandService",
    ),
    _entry(
        "logging.text_path",
        "Text log path",
        "Optional human-readable text log path.",
        source="config_yaml",
        scope="logging",
        visibility="diagnostic",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="none",
        write_boundary=None,
    ),
    _entry(
        "debug.save_full_agent_io",
        "Save full agent I/O",
        "Debug-only persistence of full agent prompts and outputs.",
        source="config_yaml",
        scope="debug",
        visibility="hidden",
        editable_v1=False,
        requires_restart=True,
        audit_behavior="future diagnostics command",
        write_boundary=None,
    ),
]
